services:
  #Prisma
  sonar:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - ./sonar-data:/opt/sonarqube/data
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    depends_on:
      - postgres

  postgres:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sonar

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: on-failure
    environment:
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    ports:
      - "27017:27017"

  app:
    image: case:v1
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: bd-chave-pix
    ports:
      - "8080:8080"
    deploy:
      replicas: 1