services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: on-failure
    environment:
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    ports:
      - "27017:27017"
  app:
    container_name: itau-case
    image: case:v1
    ports:
      - "8080:8080"
    deploy:
      replicas: 2